### ISSUE TITLE
Can't seem to create an ad

### ISSUE THREAD

**Issue by zachatkinson** [ArthurG/Kijiji-Repost-Headless#102]
Hi folks, I'm new to python but running the command

python kijiji_repost_headless build_ad

in the root folder of the project seems to generate errors for me - see attached. If anyone can point me in the right direction that would be greatly appreciated - I have no doubt I am missing something simple. (I have ensured all dependencies are installed already)

Error recieved:

ZachMacbookPro:krp zach$ python kijiji_repost_headless build_ad
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 153, in _run_module_as_main
    mod_name, loader, code, fname = _get_main_module_details()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 125, in _get_main_module_details
    return _get_module_details(main_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 113, in _get_module_details
    code = loader.get_code(mod_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 283, in get_code
    self.code = compile(source, self.filename, 'exec')
  File "/Users/zach/Downloads/krp/kijiji_repost_headless/__main__.py", line 108
    [print("{ad_id:10} {rank:4} {views:5} '{title}'".format(
         ^
SyntaxError: invalid syntax

**Comment by socialcode-rob1** [comment]
Hi @zachatkinson, I'm seeing the same issue.  What did I miss?

**Comment by zachatkinson** [comment]
Hello Rob.my issue was I was calling python instead of python3 on my Mac - calling python3 solver my issues
