### ISSUE TITLE
Cound not post ad.

### ISSUE THREAD

**Issue by mrlayance** [ArthurG/Kijiji-Repost-Headless#127]
Trying to post my first ad.

I get the following.  I don't see anything in the dump file.

`Image upload success on try #1
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "kijiji_repost_headless/__main__.py", line 195, in <module>
    main()
  File "kijiji_repost_headless/__main__.py", line 51, in main
    args.function(args)
  File "kijiji_repost_headless/__main__.py", line 95, in post_ad
    api.post_ad_using_data(data, image_files)
  File "kijiji_repost_headless/kijiji_api.py", line 201, in post_ad_using_data
    raise KijijiApiException("Could not post ad.", resp.text)
kijiji_api.KijijiApiException: Could not post ad.
See kijijiapi_dump_20181219T154248.html in current directory for latest dumpfile.`

**Comment by ArthurG** [comment]
How did you fix this error?
