### ISSUE TITLE
Script errors when trying to post item.yml

### ISSUE THREAD

**Issue by zachatkinson** [ArthurG/Kijiji-Repost-Headless#128]
Hi Guys, 

Getting script erros when trying to post a file. I am not sure if anyone can sniff out the issue here, I am a total Python noob.

````
python3 kijiji_repost_headless repost posts/7030-woodbine/item.yml

Traceback (most recent call last):
  File "/opt/alt/python35/lib64/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/alt/python35/lib64/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "kijiji_repost_headless/__main__.py", line 195, in <module>
    main()
  File "kijiji_repost_headless/__main__.py", line 51, in main
    args.function(args)
  File "kijiji_repost_headless/__main__.py", line 139, in repost_ad
    api.login(args.username, args.password)
  File "kijiji_repost_headless/kijiji_api.py", line 96, in login
    'ca.kijiji.xsrf.token': get_token(resp.text, 'ca.kijiji.xsrf.token'),
  File "kijiji_repost_headless/kijiji_api.py", line 38, in get_token
    res = soup.select("[name={}]".format(attrib_name))
  File "/home/zachatki/virtualenv/public__html_cgi-bin_tester/3.5/lib/python3.5/site-packages/bs4/element.py", line 1376, in select
    return soupsieve.select(selector, self, namespaces, limit, **kwargs)
  File "/home/zachatki/virtualenv/public__html_cgi-bin_tester/3.5/lib/python3.5/site-packages/soupsieve/__init__.py", line 108, in select
    return compile(select, namespaces, flags).select(tag, limit)
  File "/home/zachatki/virtualenv/public__html_cgi-bin_tester/3.5/lib/python3.5/site-packages/soupsieve/__init__.py", line 59, in compile
    return cp._cached_css_compile(pattern, namespaces, flags)
  File "/home/zachatki/virtualenv/public__html_cgi-bin_tester/3.5/lib/python3.5/site-packages/soupsieve/css_parser.py", line 178, in _cached_css_compile
    CSSParser(pattern, flags).process_selectors(),
  File "/home/zachatki/virtualenv/public__html_cgi-bin_tester/3.5/lib/python3.5/site-packages/soupsieve/css_parser.py", line 810, in process_selectors
    return self.parse_selectors(self.selector_iter(self.pattern), index, flags)
  File "/home/zachatki/virtualenv/public__html_cgi-bin_tester/3.5/lib/python3.5/site-packages/soupsieve/css_parser.py", line 688, in parse_selectors
    key, m = next(iselector)
  File "/home/zachatki/virtualenv/public__html_cgi-bin_tester/3.5/lib/python3.5/site-packages/soupsieve/css_parser.py", line 797, in selector_iter
    raise SyntaxError("Invlaid character {!r} at position {}".format(pattern[index], index))
SyntaxError: Invlaid character '[' at position 0

**Comment by facelessuser** [comment]
I am the author of `soupsieve` which is reporting the error you are seeing. I am temporarily doing a periodic search for issues with `soupsieve` as this is the first time it is being used as the official selector library of BeatifulSoup 4.7.0+.  My intent is to catch unreported bugs, or unintuitive errors like found in this issue.

The issue you are seeing is related to a bad selector that BeautifulSoup's old select method used to allow: `res = soup.select("[name={}]".format(attrib_name))`. `[name={}]` is not a valid attribute selector as `{}` must be quoted per the CSS spec.  `res = soup.select("[name='{}']".format(attrib_name))`. Would fix this issue.

I will most likely improve the exception messages to alert the user of a malformed attribute selector instead of just reporting the first character as invalid moving forward.  Hopefully this helped.

**Comment by zachatkinson** [comment]
Wow, thanks so much for your fast reply @facelessuser! That definitely helps, as I said, I am totally running blindly into the world of Python with this project. Excuse my ignorance, but should I go in and make these edits to the `soupsieve` file, or wait for a project update?

**Comment by facelessuser** [comment]
No, that is an error in this project, not soupsieve.  SoupSieve is complaining that this project is giving it a bad selector:

You'll find the issue here:

```
File "kijiji_repost_headless/kijiji_api.py", line 38, in get_token
    res = soup.select("[name={}]".format(attrib_name))
```

**Comment by zachatkinson** [comment]
@facelessuser wow i feel so foolish, thanks for nudging me the right direction again, didn't mean to put my work on you!

**Comment by zachatkinson** [comment]
@ArthurG not sure if this helps you at all, I'll be making the changes on my end but if you want to update the project this nice gentleman has been a great help!
