### ISSUE TITLE
Malformed attribute selector at position 0

### ISSUE THREAD

**Issue by jfcartier** [ArthurG/Kijiji-Repost-Headless#131]
Hi,
I get a script error when I try to do anything. I guess the basic command to test the program would be show command. Here's what I get.

```
~/Desktop/Kijiji $ python3 kijiji_repost_headless -u email@gmail.com -p KtHYxaf78 show

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "kijiji_repost_headless/__main__.py", line 195, in <module>
    main()
  File "kijiji_repost_headless/__main__.py", line 51, in main
    args.function(args)
  File "kijiji_repost_headless/__main__.py", line 106, in show_ads
    api.login(args.username, args.password)
  File "kijiji_repost_headless/kijiji_api.py", line 96, in login
    'ca.kijiji.xsrf.token': get_token(resp.text, 'ca.kijiji.xsrf.token'),
  File "kijiji_repost_headless/kijiji_api.py", line 38, in get_token
    res = soup.select("[name={}]".format(attrib_name))
  File "/usr/local/lib/python3.7/site-packages/bs4/element.py", line 1376, in select
    return soupsieve.select(selector, self, namespaces, limit, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/soupsieve/__init__.py", line 108, in select
    return compile(select, namespaces, flags).select(tag, limit)
  File "/usr/local/lib/python3.7/site-packages/soupsieve/__init__.py", line 59, in compile
    return cp._cached_css_compile(pattern, namespaces, flags)
  File "/usr/local/lib/python3.7/site-packages/soupsieve/css_parser.py", line 183, in _cached_css_compile
    CSSParser(pattern, flags).process_selectors(),
  File "/usr/local/lib/python3.7/site-packages/soupsieve/css_parser.py", line 854, in process_selectors
    return self.parse_selectors(self.selector_iter(self.pattern), index, flags)
  File "/usr/local/lib/python3.7/site-packages/soupsieve/css_parser.py", line 713, in parse_selectors
    key, m = next(iselector)
  File "/usr/local/lib/python3.7/site-packages/soupsieve/css_parser.py", line 841, in selector_iter
    raise SyntaxError(msg)
SyntaxError: Malformed attribute selector at position 0
```

Do you have a way to fix this or simply a workaround? 
Thanks !

**Comment by jackm** [comment]
Related to #128

**Comment by arsalansids** [comment]
Hi there! I'm also getting this error. #128 didn't give too much information either. Any idea how to post the ad without getting this error?

**Comment by jfcartier** [comment]
> Hi there! I'm also getting this error. #128 didn't give too much information either. Any idea how to post the ad without getting this error?

Hi there.
I found a workaround in this pull request : https://github.com/ArthurG/Kijiji-Repost-Headless/pull/132/commits/9a14e872ad99ca38412a088074c9223fdd4de3ce. 

Just manually make that change and it'll be fine. 

Cheers

**Comment by arsalansids** [comment]
That was perfect, thanks!
