### ISSUE TITLE
kijiji_api.KijijiApiException: Element with name attribute 'ca.kijiji.xsrf.token' not found in html text

### ISSUE THREAD

**Issue by vic-c** [ArthurG/Kijiji-Repost-Headless#137]
Greetings, first time dealing with this project, trying to get a listing of my ads as a test:
`python3 kijiji_repost_headless -u my_email -p "my_password_with_special_characters" show`

Get the following error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "kijiji_repost_headless/__main__.py", line 195, in <module>
    main()
  File "kijiji_repost_headless/__main__.py", line 51, in main
    args.function(args)
  File "kijiji_repost_headless/__main__.py", line 106, in show_ads
    api.login(args.username, args.password)
  File "kijiji_repost_headless/kijiji_api.py", line 96, in login
    'ca.kijiji.xsrf.token': get_token(resp.text, 'ca.kijiji.xsrf.token'),
  File "kijiji_repost_headless/kijiji_api.py", line 40, in get_token
    raise KijijiApiException("Element with name attribute '{}' not found in html text.".format(attrib_name), html)
kijiji_api.KijijiApiException: Element with name attribute 'ca.kijiji.xsrf.token' not found in html text.
See kijijiapi_dump_20190407T150649.html in current directory for latest dumpfile.
```

Dump is here
[kijijiapi_dump_20190407T150649.html](https://gist.github.com/vic-c/e8fbb41444cbbf7ec7a8b265aea165fc#file-kijijiapi_dump_20190407t150649-html)
 
My password has special char !. Tried both escaping it with \ or wrapping entire password with "" same result.

Thanks for any help!

**Comment by vic-c** [comment]
Hi, still can't figure it out. Wonder if someone cane take a quick look & comment. Thank you!

**Comment by jackm** [comment]
Have you tried using single quotes around the password string? Make sure you escape and single quotes that are part of the password string itself.

**Comment by vic-c** [comment]
I just tried with single quotes but result is the same. 

The only special char I have is "!" in pwd and "@" in the login. I don't think I need to escape them as long as I put the pwd or login string in "" or in ''. But I tired escaping just in case and still no luck.

**Comment by jackm** [comment]
I don't actually think this is an issue with your password at all. Normally you'd see an exception saying "Could not log in" if your credentials are not correct, however in this case it reached the exception you've shown before it was able to even complete the login function.

For some reason the scraper is not finding the unique xsrf value from the HTML. This value should be present on nearly every Kijiji site page, especially the login page. The dump file you posted even has the text "ca.kijiji.xsrf.token" in it so I'm puzzled as to why kijiji_repost_headless didn't find it.

**Comment by vic-c** [comment]
Thank for looking! 

Is there any other debug output I could collect? I don't code in python but cli / bash tasks are Ok.

**Comment by jackm** [comment]
Using a debugger that is able to make breakpoints would be best. That way you can set a breakpoint when the exception occurs and go back to look at the HTTP get requests and see the actual content returned.

**Comment by ArthurG** [comment]
I've tried my own personal account with an "!" in the password, and I never had to escape anything. 

Something weird is definitely going on with your account, though. From the dump, it looks like you're still stuck at the login page. Are you sure your account credentials are correct? Are you using a proxy, and if so, are you able to post ads normally via browser?

**Comment by bpjobin** [comment]
Any update on this? I'm trying to run the script on a synology nas (if that makes any difference) and I'm always getting this error.

```
Traceback (most recent call last):
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/volume1/homes/bpjobin/python_scripts/Kijiji-Repost-Headless/kijiji_repost_headless/__main__.py", line 195, in <module>
    main()
  File "/volume1/homes/bpjobin/python_scripts/Kijiji-Repost-Headless/kijiji_repost_headless/__main__.py", line 51, in main
    args.function(args)
  File "/volume1/homes/bpjobin/python_scripts/Kijiji-Repost-Headless/kijiji_repost_headless/__main__.py", line 139, in repost_ad
    api.login(args.username, args.password)
  File "/volume1/homes/bpjobin/python_scripts/Kijiji-Repost-Headless/kijiji_repost_headless/kijiji_api.py", line 96, in login
    'ca.kijiji.xsrf.token': get_token(resp.text, 'ca.kijiji.xsrf.token'),
  File "/volume1/homes/bpjobin/python_scripts/Kijiji-Repost-Headless/kijiji_repost_headless/kijiji_api.py", line 38, in get_token
    res = soup.select("[name={}]".format(attrib_name))
  File "/var/services/homes/bpjobin/.local/lib/python3.5/site-packages/bs4/element.py", line 1334, in select
    return soupsieve.select(selector, self, namespaces, limit, **kwargs)
  File "/var/services/homes/bpjobin/.local/lib/python3.5/site-packages/soupsieve/__init__.py", line 114, in select
    return compile(select, namespaces, flags, **kwargs).select(tag, limit)
  File "/var/services/homes/bpjobin/.local/lib/python3.5/site-packages/soupsieve/__init__.py", line 63, in compile
    return cp._cached_css_compile(pattern, namespaces, custom, flags)
  File "/var/services/homes/bpjobin/.local/lib/python3.5/site-packages/soupsieve/css_parser.py", line 214, in _cached_css_compile
    CSSParser(pattern, custom=custom_selectors, flags=flags).process_selectors(),
  File "/var/services/homes/bpjobin/.local/lib/python3.5/site-packages/soupsieve/css_parser.py", line 1113, in process_selectors
    return self.parse_selectors(self.selector_iter(self.pattern), index, flags)
  File "/var/services/homes/bpjobin/.local/lib/python3.5/site-packages/soupsieve/css_parser.py", line 946, in parse_selectors
    key, m = next(iselector)
  File "/var/services/homes/bpjobin/.local/lib/python3.5/site-packages/soupsieve/css_parser.py", line 1100, in selector_iter
    raise SelectorSyntaxError(msg, self.pattern, index)
soupsieve.util.SelectorSyntaxError: Malformed attribute selector at position 0
  line 1:
[name=ca.kijiji.xsrf.token]
```

**Comment by jackm** [comment]
@bpjobin You are not using the latest version. The problem you have is not related to this issue and was fixed back in January 2019 in PR #132.

**Comment by torqueNoFriction** [comment]
I am also experiencing the same issue 

`Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "kijiji_repost_headless\__main__.py", line 200, in <module>
    main()
  File "kijiji_repost_headless\__main__.py", line 51, in main
    args.function(args)
  File "kijiji_repost_headless\__main__.py", line 87, in post_ad
    while not check_ad(args) and attempts < 5:
  File "kijiji_repost_headless\__main__.py", line 172, in check_ad
    api.login(args.username, args.password)
  File "kijiji_repost_headless\kijiji_api.py", line 106, in login
    'ca.kijiji.xsrf.token': get_token(resp.text, 'ca.kijiji.xsrf.token'),
  File "kijiji_repost_headless\kijiji_api.py", line 50, in get_token
    raise KijijiApiException("Element with name attribute '{}' not found in html text.".format(attrib_name), html)
kijiji_api.KijijiApiException: Element with name attribute 'ca.kijiji.xsrf.token' not found in html text.
See kijijiapi_dump_20200509T181906.html in current directory for latest dumpfile.
PS D:\OneDrive\Backups\kijiji_poster\kijijiPoster>
[kijijiapi_dump_20200509T181906.zip](https://github.com/ArthurG/Kijiji-Repost-Headless/files/4604666/kijijiapi_dump_20200509T181906.zip)

`

**Comment by EEG-Brain-Scanner** [comment]
Same exact issue. I even factory reset my pc and reinstalled pip, xcode, and the requirements. Pleassseeeeeeeee help. I see this issue has remained unresolved since last year.

`Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/evanskrukwa/Desktop/kijiji_repost_headless/__main__.py", line 200, in <module>
    main()
  File "/Users/evanskrukwa/Desktop/kijiji_repost_headless/__main__.py", line 51, in main
    args.function(args)
  File "/Users/evanskrukwa/Desktop/kijiji_repost_headless/__main__.py", line 87, in post_ad
    while not check_ad(args) and attempts < 5:
  File "/Users/evanskrukwa/Desktop/kijiji_repost_headless/__main__.py", line 172, in check_ad
    api.login(args.username, args.password)
  File "/Users/evanskrukwa/Desktop/kijiji_repost_headless/kijiji_api.py", line 106, in login
    'ca.kijiji.xsrf.token': get_token(resp.text, 'ca.kijiji.xsrf.token'),
  File "/Users/evanskrukwa/Desktop/kijiji_repost_headless/kijiji_api.py", line 50, in get_token
    raise KijijiApiException("Element with name attribute '{}' not found in html text.".format(attrib_name), html)
kijiji_api.KijijiApiException: Element with name attribute 'ca.kijiji.xsrf.token' not found in html text.`

**Comment by ArthurG** [comment]
Is this related to #176 ? @EEG-Brain-Scanner

**Comment by EEG-Brain-Scanner** [comment]
Not sure the question exactly. If you are asking me on a technical aspect if they are related then I have no idea. I just pasted the python errors above that are the same errors OP posted when he opened this issue. @ArthurG

**Comment by astrion** [comment]
I think this is something to do with the Kijiji login page blocking automated login. When I log in using my account on Chrome page, the page I downloaded has 'ca.kijiji.xsrf.token' tag. However, if I connect using BS4, it returned a meaningless page-sized about 99Kbyte. The correct login page is sized about 800-900Kbyte. I believe it is related to issue #176

**Comment by EEG-Brain-Scanner** [comment]
I believe that is correct. It seems all reposters have stopped working because of the login issues.

**Comment by dbz195** [comment]
any update on this error i get the following msg


Traceback (most recent call last):
  File "C:\Users\peeronevoip\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\peeronevoip\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "kijiji_repost_headless\__main__.py", line 200, in <module>
    main()
  File "kijiji_repost_headless\__main__.py", line 51, in main
    args.function(args)
  File "kijiji_repost_headless\__main__.py", line 106, in show_ads
    api.login(args.username, args.password)
  File "kijiji_repost_headless\kijiji_api.py", line 111, in login
    "xsrfToken": get_xsrf_token(resp.text),
  File "kijiji_repost_headless\kijiji_api.py", line 84, in get_xsrf_token
    raise KijijiApiException("XSRF token not found in html text.", html)
kijiji_api.KijijiApiException: XSRF token not found in html text.
See kijijiapi_dump_20200528T145553.html in current directory for latest dumpfile.

**Comment by vic-c** [comment]
My original issue was due to some python version mismatch / having multiple versions of it on the same machine.

I'll close this issue since the original problem was resolved. 

If anyone experiences similar issues suggest to double-check python versions and path(es) and follow readme installation of PIP modules exactly. If the issue persists, pls open a new ticket.

**Comment by prgrm** [comment]
I'm also getting this error "XSRF token not found in html text" now even though it was working fine 2 days ago.
