### ISSUE TITLE
Nuke stopped working

### ISSUE THREAD

**Issue by michaelkuzmin** [ArthurG/Kijiji-Repost-Headless#147]
I just realized that in my older version show didnt work since I updated in January 2019. I updated to the newest version. Now in today's version nuke doesn't work. Here is what I get:

Microsoft Windows [Version 10.0.17763.678]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\Michael>cd C:\Routine\kijijipy

C:\Routine\kijijipy>python kijiji_repost_headless -u user@name.ca -p XXXXXX nuke
Traceback (most recent call last):
  File "C:\Users\Michael\AppData\Local\conda\conda\envs\p36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Michael\AppData\Local\conda\conda\envs\p36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "kijiji_repost_headless\__main__.py", line 204, in <module>
    main()
  File "kijiji_repost_headless\__main__.py", line 51, in main
    args.function(args)
  File "kijiji_repost_headless\__main__.py", line 196, in nuke
    [api.delete_ad(ad['id']) for ad in all_ads]
  File "kijiji_repost_headless\__main__.py", line 196, in <listcomp>
    [api.delete_ad(ad['id']) for ad in all_ads]
  File "kijiji_repost_headless\kijiji_api.py", line 128, in delete_ad
    'ca.kijiji.xsrf.token': get_xsrf_token(my_ads_page.text),
  File "kijiji_repost_headless\kijiji_api.py", line 73, in get_xsrf_token
    return yaml.load(m.group(1), Loader=yaml.FullLoader)['token']
AttributeError: module 'yaml' has no attribute 'FullLoader'

C:\Routine\kijijipy>

**Comment by jackm** [comment]
You need to update your pyyaml Python package to version 5.1 or newer.

See [here](https://stackoverflow.com/a/55553392) for details.
