### ISSUE TITLE
Build_Ad not working

### ISSUE THREAD

**Issue by AlphaNerd** [ArthurG/Kijiji-Repost-Headless#156]
I've cloned and installed all deps. When following the instruction `python kijiji_repost_headless build_ad`, I get the following error:

`Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 165, in _run_module_as_main
    mod_name, loader, code, fname = _get_main_module_details(_Error)
  File "/usr/lib/python2.7/runpy.py", line 133, in _get_main_module_details
    return _get_module_details(main_name)
  File "/usr/lib/python2.7/runpy.py", line 119, in _get_module_details
    code = loader.get_code(mod_name)
  File "/usr/lib/python2.7/pkgutil.py", line 281, in get_code
    self.code = compile(source, self.filename, 'exec')
  File "/home/alphanerd/Github/Kijiji-Repost-Headless/kijiji_repost_headless/__main__.py", line 110
    [print("{ad_id:10} {rank:4} {views:5} '{title}'".format(
         ^
SyntaxError: invalid syntax`

**Comment by ArthurG** [comment]
Use python 3 instead
