### ISSUE TITLE
Getting started guide not working

### ISSUE THREAD

**Issue by fandy** [ArthurG/Kijiji-Repost-Headless#171]
after installing requirements.txt, it does not work out the box.
```
➜  Kijiji-Repost-Headless git:(master) python kijiji_repost_headless build_ad
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 165, in _run_module_as_main
    mod_name, loader, code, fname = _get_main_module_details(_Error)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 133, in _get_main_module_details
    return _get_module_details(main_name)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 119, in _get_module_details
    code = loader.get_code(mod_name)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 281, in get_code
    self.code = compile(source, self.filename, 'exec')
  File "/Users/fang/Kijiji-Repost-Headless/kijiji_repost_headless/__main__.py", line 110
    [print("{ad_id:10} {rank:4} {views:5} '{title}'".format(
         ^
SyntaxError: invalid syntax
```

**Comment by fandy** [comment]
Ah I see, gotta use Python3.
