### ISSUE TITLE
KijijiApiException("Could not log in."

### ISSUE THREAD

**Issue by EEG-Brain-Scanner** [ArthurG/Kijiji-Repost-Headless#186]
I have triple checked that all dependancies are correct version (py 3.7.7 pyyaml 5.1.1) and that my username and password are correct. When ever I try to do anything (repost, post, show) I get this error.

`Traceback (most recent call last):
  File "/opt/anaconda3/envs/KijijiEnv/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/anaconda3/envs/KijijiEnv/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/evanskrukwa/Documents/Kijiji/kijiji_repost_headless/__main__.py", line 203, in <module>
    main()
  File "/Users/evanskrukwa/Documents/Kijiji/kijiji_repost_headless/__main__.py", line 51, in main
    args.function(args)
  File "/Users/evanskrukwa/Documents/Kijiji/kijiji_repost_headless/__main__.py", line 109, in show_ads
    api.login(args.username, args.password)
  File "/Users/evanskrukwa/Documents/Kijiji/kijiji_repost_headless/kijiji_api.py", line 121, in login
    raise KijijiApiException("Could not log in.", resp.text)
kijiji_api.KijijiApiException: Could not log in.`

Dump file contains
`{"errors":[{"message":"Variable \"$input\" got invalid value \"NEW_AJAX_LOGIN\" at \"input.hints[0]\"; Expected type Hints.","locations":[{"line":1,"column":20}],"extensions":{"errorCode":"INTERNAL_SERVER_ERROR"}}]}`

Thanks

**Comment by ArthurG** [comment]
Seems related to #185
