### ISSUE TITLE
Posting not working : got invalid value \"NEW_AJAX_LOGIN

### ISSUE THREAD

**Issue by vogt** [ArthurG/Kijiji-Repost-Headless#188]
When I try to post and repost a new ad, I got a error message :

`
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "kijiji_repost_headless/__main__.py", line 203, in <module>
    main()
  File "kijiji_repost_headless/__main__.py", line 51, in main
    args.function(args)
  File "kijiji_repost_headless/__main__.py", line 149, in repost_ad
    delete_ad(args, api)
  File "kijiji_repost_headless/__main__.py", line 130, in delete_ad
    api.login(args.username, args.password)
  File "kijiji_repost_headless/kijiji_api.py", line 121, in login
    raise KijijiApiException("Could not log in.", resp.text)
kijiji_api.KijijiApiException: Could not log in.
See kijijiapi_dump_20200719T165553.html in current directory for latest dumpfile.
`

Here is the ouput of the html dump file for example :
`
{"errors":[{"message":"Variable \"$input\" got invalid value \"NEW_AJAX_LOGIN\" at \"input.hints[0]\"; Expected type Hints.","locations":[{"line":1,"column":20}],"extensions":{"errorCode":"INTERNAL_SERVER_ERROR"}}]}
`

Am I doing something wrong? Or has the login system changed?

**Comment by ArthurG** [comment]
Are you on the latest master?

**Comment by vogt** [comment]
No I was not -_-'
It's working perfectly fine.
