### ISSUE TITLE
Could not log in.

### ISSUE THREAD

**Issue by EEG-Brain-Scanner** [ArthurG/Kijiji-Repost-Headless#190]
worked yesterday for me but today this (trying to repost):

Traceback (most recent call last):
  File "/opt/anaconda3/envs/Kijiji/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/anaconda3/envs/Kijiji/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/evanskrukwa/Documents/Kijiji/kijiji_repost_headless/__main__.py", line 203, in <module>
    main()
  File "/Users/evanskrukwa/Documents/Kijiji/kijiji_repost_headless/__main__.py", line 51, in main
    args.function(args)
  File "/Users/evanskrukwa/Documents/Kijiji/kijiji_repost_headless/__main__.py", line 149, in repost_ad
    delete_ad(args, api)
  File "/Users/evanskrukwa/Documents/Kijiji/kijiji_repost_headless/__main__.py", line 130, in delete_ad
    api.login(args.username, args.password)
  File "/Users/evanskrukwa/Documents/Kijiji/kijiji_repost_headless/kijiji_api.py", line 120, in login
    raise KijijiApiException("Could not log in.", resp.text)
kijiji_api.KijijiApiException: Could not log in.

**Comment by EEG-Brain-Scanner** [comment]
after further troubleshooting, it was fixed by reformatting my description in the .yaml file.
