### ISSUE TITLE
Error posting Ad: "We're listening, learning and taking action"

### ISSUE THREAD

**Issue by davehcdn** [ArthurG/Kijiji-Repost-Headless#194]
When I try post an ad the images upload and then:

>Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "kijiji_repost_headless/__main__.py", line 203, in <module>
    main()
  File "kijiji_repost_headless/__main__.py", line 51, in main
    args.function(args)
  File "kijiji_repost_headless/__main__.py", line 98, in post_ad
    api.post_ad_using_data(data, image_files)
  File "kijiji_repost_headless/kijiji_api.py", line 234, in post_ad_using_data
    raise KijijiApiException("Could not post ad.", resp.text)
kijiji_api.KijijiApiException: Could not post ad.
See kijijiapi_dump_20200820T152352.html in current directory for latest dumpfile.

The dumpfile is displays this: (cant attach html doc )
<img width="582" alt="Screen Shot 2020-08-20 at 3 30 40 PM" src="https://user-images.githubusercontent.com/69987901/90816391-2e9d8d00-e2fa-11ea-999e-1a7ae7ca8388.png">

**Comment by kheniparth** [comment]
@davehcdn  I think the login is failing because the login request payload is missing recaptchaResponse parameter that is newly added by Kijiji recently.

![image](https://user-images.githubusercontent.com/6601149/95402034-b9ebd580-08dc-11eb-9ead-3ab7a3e2c809.png)

**Comment by ArthurG** [comment]
This is likely related to #198. Please comment on that one if it is related.

**Comment by davehcdn** [comment]
Wow, seems like the SSID fixed the problem!  I finally have this thing working and successfully posting ads. @ArthurG
