### ISSUE TITLE
"Could not log in"

### ISSUE THREAD

**Issue by Corgano** [ArthurG/Kijiji-Repost-Headless#207]
Im getting a very generic "could not log in" error when i try to reupload ads.
`python kijiji_repost_headless -s ssid.txt repost ads\Switch\item.yml
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "kijiji_repost_headless\__main__.py", line 193, in <module>
    main()
  File "kijiji_repost_headless\__main__.py", line 50, in main
    args.function(args)
  File "kijiji_repost_headless\__main__.py", line 140, in repost_ad
    delete_ad(args, api)
  File "kijiji_repost_headless\__main__.py", line 121, in delete_ad
    api.login(args.ssid)
  File "kijiji_repost_headless\kijiji_api.py", line 107, in login
    raise KijijiApiException("Could not log in.")
kijiji_api.KijijiApiException: Could not log in.`
I already put my SSID in SSID.txt. I got it using chrome dev tools -> applications tab -> cookies in the tree on the left. Any ideas?

**Comment by Phibins** [comment]
Did you try updating the SSID string?

**Comment by Corgano** [comment]
I tried logging out and logging in to see if it would change

**Comment by Aluui** [comment]
Look for the ssid value not the SSID value.

Also ignore the ssid1, ssid2 or other number values

**Comment by PescoTan** [comment]
I started having this issue yesterday. I have tried ssids from multiple sessions & computers. 

same error message:


Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "kijiji_repost_headless/__main__.py", line 193, in <module>
    main()
  File "kijiji_repost_headless/__main__.py", line 50, in main
    args.function(args)
  File "kijiji_repost_headless/__main__.py", line 101, in show_ads
    api.login(args.ssid)
  File "kijiji_repost_headless/kijiji_api.py", line 107, in login
    raise KijijiApiException("Could not log in.")
kijiji_api.KijijiApiException: Could not log in.

**Comment by prgrm** [comment]
@PescoTan I'm having the same issue. It started happening this morning after weeks of no issues.
