### ISSUE TITLE
Nuke stopped working now

### ISSUE THREAD

**Issue by AlexZhouAA** [ArthurG/Kijiji-Repost-Headless#210]
I'm using the latest version. The nuke function suddenly stop working.
However, show and post work perfectly.
<pre>python kijiji_repost_headless -s ssid.txt nuke
Traceback (most recent call last):
	File "C:\....\lib\runpy.py", line 193, in _run_module_as_main "__main__", mod_spec)
	File "C:\....\lib\runpy.py", line 85, in _run_code exec(code, run_globals)
	File "kijiji_repost_headless\__main__.py", line 193, in <module> main()
	File "kijiji_repost_headless\__main__.py", line 50, in main args.function(args)
	File "kijiji_repost_headless\__main__.py", line 185, in nuke [api.delete_ad(ad['id']) for ad in all_ads]
	File "kijiji_repost_headless\__main__.py", line 185, in <listcomp> [api.delete_ad(ad['id']) for ad in all_ads]
	File "kijiji_repost_headless\kijiji_api.py", line 136, in delete_ad 'ca.kijiji.xsrf.token': get_xsrf_token(my_ads_page.text),
	File "kijiji_repost_headless\kijiji_api.py", line 85, in get_xsrf_token
		raise KijijiApiException("XSRF token not found in html text.", html)
kijiji_api.KijijiApiException: XSRF token not found in html text.
See kijijiapi_dump_20210129T150006.html in current directory for latest dumpfile.
</pre>

Please advise

**Comment by prgrm** [comment]
Posting and deleting stopped working for me a couple of days ago. show is the only thing that works for me!

**Comment by zalmoxis** [comment]
I'm having the same issue when running delete. I tried to use the "get_token" function as it's mentioned that is the conventional way to get the xsrf tokens except for the delete page, but it did not fix it. I assume that they updated the way they hide the xsrf token in the my ads page. Any hints?

**Comment by prgrm** [comment]
Is anyone else able to post or delete? When I try to delete I get "Did not find an existing ad with matching title, skipping ad deletion" message. When I try to post I don't get any errors but it doesn't even try to upload the images. It just exits the script without errors. The dump file doesn't contain any error messages either.

**Comment by Phibins** [comment]
I have the same error.

I have to delete manually on the website, then repost the ad.

**Comment by prgrm** [comment]
@Phibins Thank you for your reply. I just tried deleting manually first and the posting function now works. So it seems only nuke and delete functions are broken.

**Comment by zalmoxis** [comment]
By the looks of it the xsrf token is listed somewhere else now?
[https://puu.sh/HdMdl/871e6ebd10.png](url)
After you click "Delete > Prefer not to say" you expose the Delete Listing button. In the js console you can see an XHR POST request to https://www.kijiji.ca/j-page-view.json that has in the headers this token:
"x-ebay-box-token" : "1612494733513.519878e57577e7a9f50f0c53fbdcccccc8411221ffa6cd316a19cf917f7bd05e"
As far as I can tell this is a XSRF token (13 numeric DOT 64 alphanumeric).
It seems like this POST request is made when you initially click the "Delete" link or trash button on the posting. If someone can figure out what javascript gets called to make this request maybe we can fix this.

I should also mention that this XHR POST request is always preceded by an XHR HEAD request to https://www.kijiji.ca/j-token-gen.json

Any ideas?

**Comment by zalmoxis** [comment]
Actually I figured it out - the response to the HEAD request contains the XSRF token. I created a patch and here's the patch

https://github.com/zalmoxis/Kijiji-Repost-Headless/commit/00249925049ad5e94df69346c813ab417e13a0f7

**Comment by AlexZhouAA** [comment]
@zalmoxis Perfect, now it's up and running. Thank you so much

**Comment by benjaminolenick** [comment]
> Actually I figured it out - the response to the HEAD request contains the XSRF token. I created a patch fix:
> [zalmoxis@0024992](https://github.com/zalmoxis/Kijiji-Repost-Headless/commit/00249925049ad5e94df69346c813ab417e13a0f7)
> 
> Also, if you're on linux (and maybe not headless), install sxiv image viewer and check out this fork
> https://github.com/zalmoxis/Kijiji-Repost-Headless/
> 
> FYI, in SXIV gallery view M marks the file, arrow keys select, and q exits and continues with the marked files.

What's youre BTC address, I'm buying you a coffee/beer

**Comment by zalmoxis** [comment]
> > Actually I figured it out - the response to the HEAD request contains the XSRF token. I created a patch fix:
> > [zalmoxis@0024992](https://github.com/zalmoxis/Kijiji-Repost-Headless/commit/00249925049ad5e94df69346c813ab417e13a0f7)
> > Also, if you're on linux (and maybe not headless), install sxiv image viewer and check out this fork
> > https://github.com/zalmoxis/Kijiji-Repost-Headless/
> > FYI, in SXIV gallery view M marks the file, arrow keys select, and q exits and continues with the marked files.
> 
> What's youre BTC address, I'm buying you a coffee/beer

Thanks Ben! 1qclckcuxxafxq0jnjmxl5tfgzya7c2nlqqfyd3e
