### ISSUE TITLE
Could not log in using the SSID method

### ISSUE THREAD

**Issue by torqueNoFriction** [ArthurG/Kijiji-Repost-Headless#217]
I have switched properly over to the new log in method with SSID and it has been working for a few months. Recently I started to get a failure again saying could not log in again

`PS C:\kijiji_poster\kijijiPoster> python .\kijiji_repost_headless repost ..\thinkprotection.yml
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File ".\kijiji_repost_headless\__main__.py", line 193, in <module>
    main()
  File ".\kijiji_repost_headless\__main__.py", line 50, in main
    args.function(args)
  File ".\kijiji_repost_headless\__main__.py", line 140, in repost_ad
    delete_ad(args, api)
  File ".\kijiji_repost_headless\__main__.py", line 121, in delete_ad
    api.login(args.ssid)
  File ".\kijiji_repost_headless\kijiji_api.py", line 107, in login
    raise KijijiApiException("Could not log in.")
kijiji_api.KijijiApiException: Could not log in.`

**Comment by jzsecl** [comment]
I observed the same behaviour, started happening Apr 1, probably a change on the Kijiji side

**Comment by ElLuis** [comment]
Same issue

**Comment by EdwardOak** [comment]
Same issue. RIP

**Comment by EdwardOak** [comment]
Did someone monitor the traffic to see what's the issue?

**Comment by jackm** [comment]
In general, scraping HTML content for automating is always going to be prone to breaking anytime Kijiji decides to update or change something. It is a constant race of fixing bugs each time Kijiji makes a change to make sure that it still functions. This has happened many times before on this project until someone puts in the effort to find the problem and fix it again. 
A better solution is to use Kijiji's own API which they use internally, which would be _much_ more stable especially if you keep using the same API version.

**Comment by EdwardOak** [comment]
Can someone help me, I'm trying to tweak the kijiji-api.py code to use user:pass:captchasolver but I am running into issues.

**Comment by matrix303** [comment]
Same here tried multiple cookie ssids from multiple computers... same reseult

**Comment by matrix303** [comment]
> In general, scraping HTML content for automating is always going to be prone to breaking anytime Kijiji decides to update or change something. It is a constant race of fixing bugs each time Kijiji makes a change to make sure that it still functions. This has happened many times before on this project until someone puts in the effort to find the problem and fix it again.
> A better solution is to use Kijiji's own API which they use internally, which would be _much_ more stable especially if you keep using the same API version.

I would agree, that would be a better solution however I don't think we have access to that right? or is there a workaround that I am unaware of?

**Comment by williamfu4github** [comment]
+1.  Same issue. can't login with SSID

**Comment by EdwardOak** [comment]
Please, I need a regular decent python coder, I have all the pieces of code to fix this issues. I had used an alternate auth-method which worked flawlessly and I'm quasi-certain can fix this issue but I'm having trouble putting all the pieces back together.

**Comment by jackm** [comment]
> I would agree, that would be a better solution however I don't think we have access to that right? or is there a workaround that I am unaware of?

Kijiji uses an internal API on their mobile apps.
The [kijiji-manager](https://github.com/jackm/kijiji-manager) Python package uses Kijiji's internal API to communicate with Kijiji's backend. It runs a local web server where you manage your ads. Disclaimer: I am the author and maintainer of this project.

**Comment by EdwardOak** [comment]
> > I would agree, that would be a better solution however I don't think we have access to that right? or is there a workaround that I am unaware of?
> 
> Kijiji uses an internal API on their mobile apps.
> The [kijiji-manager](https://github.com/jackm/kijiji-manager) Python package uses Kijiji's internal API to communicate with Kijiji's backend. It runs a local web server where you manage your ads. Disclaimer: I am the author and maintainer of this project.

I'm testing now. Do you have any contact info or do I report issues in the appropriate github section?

Thank you for your work, btw.

**Comment by rockerguy1978** [comment]
> 
> 
> > I would agree, that would be a better solution however I don't think we have access to that right? or is there a workaround that I am unaware of?
> 
> Kijiji uses an internal API on their mobile apps.
> The [kijiji-manager](https://github.com/jackm/kijiji-manager) Python package uses Kijiji's internal API to communicate with Kijiji's backend. It runs a local web server where you manage your ads. Disclaimer: I am the author and maintainer of this project.

Just tested that project. Working well. I set it up as a service on a raspberry Pi

**Comment by EdwardOak** [comment]
> > > I would agree, that would be a better solution however I don't think we have access to that right? or is there a workaround that I am unaware of?
> > 
> > 
> > Kijiji uses an internal API on their mobile apps.
> > The [kijiji-manager](https://github.com/jackm/kijiji-manager) Python package uses Kijiji's internal API to communicate with Kijiji's backend. It runs a local web server where you manage your ads. Disclaimer: I am the author and maintainer of this project.
> 
> Just tested that project. Working well. I set it up as a service on a raspberry Pi

I'm not getting past installation. Ubuntu 18.04.

**Comment by prgrm** [comment]
> > I would agree, that would be a better solution however I don't think we have access to that right? or is there a workaround that I am unaware of?
> 
> Kijiji uses an internal API on their mobile apps.
> The [kijiji-manager](https://github.com/jackm/kijiji-manager) Python package uses Kijiji's internal API to communicate with Kijiji's backend. It runs a local web server where you manage your ads. Disclaimer: I am the author and maintainer of this project.

I just tried it and I'm really impressed. I set it up in WSL (Ubuntu 20.04.2 LTS) in Windows 10.  My only question is, do I have to create an xml file manually for each ad, or can it repost ads it finds in my kijiji account?

**Comment by matrix303** [comment]
> > 
> 
> > 
> 
> > > I would agree, that would be a better solution however I don't think we have access to that right? or is there a workaround that I am unaware of?
> 
> > 
> 
> > Kijiji uses an internal API on their mobile apps.
> 
> > The [kijiji-manager](https://github.com/jackm/kijiji-manager) Python package uses Kijiji's internal API to communicate with Kijiji's backend. It runs a local web server where you manage your ads. Disclaimer: I am the author and maintainer of this project.
> 
> 
> 
> Just tested that project. Working well. I set it up as a service on a raspberry Pi

Could you specify how you set it up as a service on RPI

**Comment by rockerguy1978** [comment]
> 
> 
> > > 
> > 
> > 
> > > 
> > 
> > 
> > > > I would agree, that would be a better solution however I don't think we have access to that right? or is there a workaround that I am unaware of?
> > 
> > 
> > > 
> > 
> > 
> > > Kijiji uses an internal API on their mobile apps.
> > 
> > 
> > > The [kijiji-manager](https://github.com/jackm/kijiji-manager) Python package uses Kijiji's internal API to communicate with Kijiji's backend. It runs a local web server where you manage your ads. Disclaimer: I am the author and maintainer of this project.
> > 
> > 
> > Just tested that project. Working well. I set it up as a service on a raspberry Pi
> 
> Could you specify how you set it up as a service on RPI



Hi @matrix303,

I am using a Raspberry Pi 3B I believe. I am running Ubuntu off of it. Hopefully this helps you and others.

I followed the project's installation instructions. I created a folder off of my user directory, then git cloned the repo, then initialized and activated a virtual environment for it. After that, I downloaded the packages defined in the projects `requirements.txt` file.


I then made my service file (`kijiji_manager.service`) in `/etc/systemd/systemd/` directory. Feel free to call you service file whatever you please.

##### Service File Example
```
[Unit]
Description=Kijiji-manager webserver
After=network.target

[Service]
WorkingDirectory=/home/ubuntu/scripts/new_kijijireposter/kijiji-manager
Environment="PATH=/home/ubuntu/scripts/new_kijijireposter/.venv/bin"
ExecStart=/home/ubuntu/scripts/new_kijijireposter/.venv/bin/python3 -m kijiji_manager -b 0.0.0.0
TimeoutSec=300

[Install]
WantedBy=multi-user.target
```

WorkingDirectory: the directory where the kijiji-manager project is
Environment: Path to your virtual environment activation file I believe. In ubuntu, it is in `<venv_dir_name>/bin/`
ExecStart: This actually runs the package (in the working directory specified in the WorkingDirectory variable). Ensure you run it with the `-b 0.0.0.0` argument. This will allow you to access the project from another system other than localhost which is the default.

After that is ran the following commands:

To launch the service: `sudo systemctl start kijiji_manager.service`
To check on the status of the service: `sudo systemctl status kijiji_manager.service`
To enable the service to automatically start if your system unintentionally loses power `sudo systemctl enable kijiji_manager.service`. If you do not do this you will have to manually start the service every time it goes down (intentional or not).

If you need to review logs of your service use: `sudo journalctl -u kijiji_manager.service`

Obviously, replace `kijiji_manager.service` with whatever you call your service file on your system.

**Comment by JohnBakery** [comment]
To fix the issues change URL `https://www.kijiji.ca/my/ads.json` to `https://www.kijiji.ca/my/ads` in `kijiji_api.py`. There are two instances of the old URL in that file.

**Comment by AminDhouib** [comment]
@JohnBakery The fix works! Thank you so much. Anybody else can confirm that it is working from their side? If so we should make a pull request that includes your fix.

**Comment by ElLuis** [comment]
It compiled for me aswell.

**Comment by astrion** [comment]
@JohnBakery It works. Thanks!

**Comment by ElLuis** [comment]
It has stopped working for me

**Comment by Aluui** [comment]
@JohnBakery This works. We can close this issue as resolved now
