### ISSUE TITLE
delete single ad not working

### ISSUE THREAD

**Issue by randallvfx** [ArthurG/Kijiji-Repost-Headless#222]
Hello Im getting the error : 
Traceback (most recent call last):
  File "/Users/randallrosa/.pyenv/versions/3.7.4/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/randallrosa/.pyenv/versions/3.7.4/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "kijiji_repost_headless/__main__.py", line 193, in <module>
    main()
  File "kijiji_repost_headless/__main__.py", line 50, in main
    args.function(args)
  File "kijiji_repost_headless/__main__.py", line 117, in delete_ad
    [data, _] = get_post_details(args.ad_file)
  File "kijiji_repost_headless/__main__.py", line 59, in get_post_details
    with open(ad_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '1568261539'

The ID number matches the 'show' command , and the ID in the URL.

Any tips appreciated!

Randall

**Comment by alumbs** [comment]
having the same issue
