### ISSUE TITLE
generate_inf_file() takes 0 positional arguments but 1 was given

### ISSUE THREAD

**Issue by dahliablue** [ArthurG/Kijiji-Repost-Headless#57]
trying to run build_ad command and keep receiving this error... sorry for n3wb question.

LOG:
```
C:\Users\Erich\Desktop\kijiji ads\Kijiji-Repost-Headless-master>python kijiji_repost_headless build_ad
Traceback (most recent call last):
  File "C:\Users\Erich\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Erich\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "kijiji_repost_headless\__main__.py", line 196, in <module>
    main()
  File "kijiji_repost_headless\__main__.py", line 55, in main
    args.function(args)
TypeError: generate_inf_file() takes 0 positional arguments but 1 was given
```

**Comment by dahliablue** [comment]
ended up running python generate_inf_file.py from its directory not sure if thats what i was supposed to do...
