### ISSUE TITLE
post error:

### ISSUE THREAD

**Issue by QwertyCoolMT** [ArthurG/Kijiji-Repost-Headless#59]
getting this error text when using the post command after having built inf file and img is in the same directory as it. obviously my actual usr+pw used.

```
>>python kijiji_repost_headless -u (username) -p (password) post item.inf

Traceback (most recent call last):
  File "C:\Users\erich\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Erich\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "kijiji_repost_headless\__main__.py", line 196, in <module>
    main()
  File "kijiji_repost_headless\__main__.py", line 55, in main
    args.function(args)
  File "kijiji_repost_headless\__main__.py", line 96, in post_ad
    while not check_ad(args) and attempts < 5:
  File "kijiji_repost_headless\__main__.py", line 177, in check_ad
    all_ads = api.get_all_ads()
  File "kijiji_repost_headless\kijiji_api.py", line 213, in get_all_ads
    user_id = get_kj_data(resp.text)['config']['userId']
KeyError: 'userId'

```

**Comment by returnzer0** [comment]
try running with python3 command instead of python

**Comment by dahliablue** [comment]
kijiji_api.py line 211:
was:         user_id = get_kj_data(resp.text)['config']['userId']
fixed:         user_id = get_kj_data(resp.text)['config']['searchForm']['userId']

**Comment by jackm** [comment]
Perhaps this could this be from a very recent change on the Kijiji site? I
thought I had this working just a few days ago.
