### ISSUE TITLE
Can not submit AD because of image

### ISSUE THREAD

**Issue by cajoy** [ArthurG/Kijiji-Repost-Headless#78]
Tried to submit AD, but can't , here is stack trace. Related to image upload:

```
Note: A recent update has broken all previously generated .inf files. Please regenerate all your files - this script is not backwards compatible with previous versions. The commands are also changed. See README for details.
Image upload success on try #1
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "kijiji_repost_headless/__main__.py", line 184, in <module>
    main()
  File "kijiji_repost_headless/__main__.py", line 50, in main
    args.function(args)
  File "kijiji_repost_headless/__main__.py", line 91, in post_ad
    api.post_ad_using_data(data, image_files)
  File "kijiji_repost_headless/kijiji_api.py", line 201, in post_ad_using_data
    raise KijijiApiException("Could not post ad.", resp.text)
kijiji_api.KijijiApiException: Could not post ad.
```

**Comment by jackm** [comment]
Open the `kijijiapi_dump_########.txt` file that was generated in your browser (it should be html) and see if the Kijiji page shows any error messages.

Often this is because there is a missing form field or there was some incorrect input on one of the fields.

**Comment by cajoy** [comment]
I've opened files and spend much time to figure out what's wrong. 

But I don't see any errors. What exactly I should search for?

**Comment by cajoy** [comment]
Might be related to following 

```
            </style>
            Please correct the following before continuing:<ul class="post-ad-layout">
                <li class="category">
                <label>Select Category:</label>

                <div class="form-section">
                        <strong>
                                Buy & Sell</strong>
                        
                            &gt;
                        <strong>
                                Computer Accessories</strong>
                        
                            &gt;
                        <strong>
                                Mice, Keyboards & Webcams</strong>
                        <a href="/p-select-category.html"
                           id="PostAdChangeCategory" class="post-ad-begin" data-btn-loc="pst-chng-cat">Change category</a>
                    </div>
            </li>
```

**Comment by cajoy** [comment]
Seems like categories mapping is out of date, 

How to sync it?

**Comment by jackm** [comment]
"Computer Accessories" > "Mice, Keyboards & Webcams" should be category ID 781

You should be able to open the dump file in your browser (you may need to change the file extension to `.html`) and then it should be easier to see what the errors are once your browser has rendered the page.

From the snippet you posted I'm not seeing anything conclusive yet as to what the problem might be.
