### ISSUE TITLE
run_tests fails.

### ISSUE THREAD

**Issue by sgbotsford** [ArthurG/Kijiji-Repost-Headless#89]
bash-3.2# ./run_tests 
E
======================================================================
ERROR: tests.test_generate_inf (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_generate_inf
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/Volumes/User_Raid/sherwood/bin/Kijiji-Repost-Headless-master/tests/test_generate_inf.py", line 3, in <module>
    from kijiji_repost_headless.generate_inf_file import get_description
ModuleNotFoundError: No module named 'kijiji_repost_headless.generate_inf_file'

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)

OS: bash-3.2# uname -a
Darwin sftf.mirkwood.local 14.5.0 Darwin Kernel Version 14.5.0: Sun Jun  4 21:40:08 PDT 2017; root:xnu-2782.70.3~1/RELEASE_X86_64 x86_64

bash-3.2# python --version
Python 3.6.5

**Comment by ArthurG** [comment]
I fixed this.

**Comment by scsikid** [comment]
any idea how this was fixed?
