### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by MaximumPotato** [ArthurG/Kijiji-Repost-Headless#90]
I'm attempting to run the script on Windows. I've generated the yml file and tried running both in CMD and Powershell, but get the same error either way. Any ideas?

```
>python kijiji_repost_headless post "D:\Library\downloads\Nexus Ad\item.yml"
Note: A recent update has broken all previously generated .inf files. Please regenerate all your files - this script is not backwards compatible with previous versions. The commands are also changed. See README for details.
Image upload success on try #1
Image upload success on try #1
Image upload success on try #1
Traceback (most recent call last):
  File "C:\Users\Core\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Core\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "kijiji_repost_headless\__main__.py", line 191, in <module>
    main()
  File "kijiji_repost_headless\__main__.py", line 50, in main
    args.function(args)
  File "kijiji_repost_headless\__main__.py", line 91, in post_ad
    api.post_ad_using_data(data, image_files)
  File "kijiji_repost_headless\kijiji_api.py", line 201, in post_ad_using_data
    raise KijijiApiException("Could not post ad.", resp.text)
  File "kijiji_repost_headless\kijiji_api.py", line 24, in __init__
    f.write(dump)
  File "C:\Users\Core\AppData\Local\Programs\Python\Python36-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 54822-54823: character maps to <undefined>
```

**Comment by MaximumPotato** [comment]
This is the same problem as posted in #11, only I don't have any special characters. At least none that I can see.

**Comment by MaximumPotato** [comment]
The error stack looked a little funky to me, thanks for clearing that up.

The "enter your address" field threw me for a loop it seems. I gave it my street, but it looks like it actually wanted just the postal code. It was trying to enter my location as somewhere in Boston. Changing that bit of text might be a nice QoL change? :P

Thanks for the help.

**Comment by jackm** [comment]
Yes, the "build" subcommand prompts should be reviewed and updated in that case.
