### ISSUE TITLE
run_tests fails.

### ISSUE THREAD

**Issue by Spazmic** [ArthurG/Kijiji-Repost-Headless#96]
======================================================================
ERROR: tests.test_generate_inf (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_generate_inf
Traceback (most recent call last):
  File "/usr/lib/python3.5/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/spazmic/Kijiji-Repost-Headless-master/tests/test_generate_inf.py", line 3, in <module>
    from kijiji_repost_headless.generate_post_file import get_description
  File "/home/spazmic/Kijiji-Repost-Headless-master/kijiji_repost_headless/generate_post_file.py", line 11, in <module>
    from get_ids import get_location_and_area_ids
ImportError: No module named 'get_ids'

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)

**Comment by ArthurG** [comment]
#152 fixes this
