### ISSUE TITLE
Dog adoption category is not working

### ISSUE THREAD

**Issue by michaelkuzmin** [ArthurG/Kijiji-Repost-Headless#97]
1) I am trying to use an older version of KRH and I am getting this file (login password removed)
`PostalLat: '43.7559808'
PostalLng: '-79.41077949999999'
categoryId: '126'
locationLevel0: 1700272
postAdForm.adType: OFFER
postAdForm.addressCity: Toronto
postAdForm.addressPostalCode: M2N5V7
postAdForm.addressProvince: 'ON'
postAdForm.attributeMap[birthdate]: "July 1, 2017"
postAdForm.attributeMap[petofferedby_s]: shelter
postAdForm.city: Toronto
postAdForm.description: "Hi, Im Cookie and I need a new home"
postAdForm.geocodeLat: '43.7559808'
postAdForm.geocodeLng: '-79.41077949999999'
postAdForm.locationId: 1700273
postAdForm.postalCode: M2N5V7
postAdForm.priceType: GIVE_AWAY
postAdForm.province: 'ON'
postAdForm.title: Dog for adoption
submitType: saveAndCheckout
topAdDuration: '7'
username: michael@gmail.com
password: 'psw123'`

When I try to post I get an error

> C:\Routine\kijijipy>python kijiji_repost_headless post C:\Routine\kijijipy\dogtest.yml
> Image upload success on try #1
> Traceback (most recent call last):
>   File "C:\Users\Michael\AppData\Local\conda\conda\envs\p36\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "C:\Users\Michael\AppData\Local\conda\conda\envs\p36\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "kijiji_repost_headless\__main__.py", line 183, in <module>
>     main()
>   File "kijiji_repost_headless\__main__.py", line 50, in main
>     args.function(args)
>   File "kijiji_repost_headless\__main__.py", line 91, in post_ad
>     api.post_ad_using_data(data, image_files)
>   File "kijiji_repost_headless\kijiji_api.py", line 201, in post_ad_using_data
>     raise KijijiApiException("Could not post ad.", resp.text)
>   File "kijiji_repost_headless\kijiji_api.py", line 24, in __init__
>     f.write(dump)
>   File "C:\Users\Michael\AppData\Local\conda\conda\envs\p36\lib\encodings\cp1251.py", line 19, in encode
>     return codecs.charmap_encode(input,self.errors,encoding_table)[0]
> UnicodeEncodeError: 'charmap' codec can't encode character '\xe7' in position 19966: character maps to <undefined>

Then when I try to generate an yml using the most recent version I can't create a yml at all, it tells me that Google Maps API needs a API key. So I cut out the code completely but I am still getting the same issue. I also noticed that the actual form doe not have a give away option so I tried replacing the price with 1 dollar but the error is still the same. 

**Can someone please help me create a valid YML file for dog giveaway category?** I can edit the values manually.

**Comment by jackm** [comment]
Could you post the Google Maps API error message?

**Comment by michaelkuzmin** [comment]
@jackm can't replicate right now. Probably because currently, the number of API calls is under some threshold. Still, with the newest version the radio is not being handled correctly (it's asking me a question for every choice of the radio button and I can't put 0 because 0 restarts it) and even if I fix this manually in the YML file I still get the same error about \xe7 character.

**Comment by jackm** [comment]
The `UnicodeEncodeError` is actually not the real problem but rather another unrelated error (soon to be fixed with a PR #98 I just made).

The actual problem is where the `KijijiApiException` error is thrown with the message "_Could not post ad._". This usually happens when Kijiji is expecting some extra fields for the ad that were not present, which is commonly found for any ads that aren't the usual buy&sell type.

In the mean time, you could manually implement the [changes in PR #98](https://github.com/ArthurG/Kijiji-Repost-Headless/pull/98/files) to fix the encoding problem, and then open the dump file in your browser to look at what errors the Kijiji site shows.

**Comment by michaelkuzmin** [comment]
@jackm what about the part where the script handles the radio buttons incorrectly, asking a separate question for each bullet point? I'm not sure, maybe I am not fixing the YML file correctly. I tried to post in that category manually and look at what's being submitted, what I have in YML seems fine but I'm not totally sure...

**Comment by jackm** [comment]
That is likely an issue with how the `kijiji_categories_attrs.json` file is generated. Some of the categories are not grouped together properly which I believe is causing the issue.

The `save_attribute_map_to_json.py` script is outdated and is in need of a re-work.

**Comment by jackm** [comment]
For your particular case when posting an ad for the "Dogs & Puppies for Rehoming" category, you should add the following additional key to the yaml ad file.

* Key name: `postAdForm.attributeMap[petofferedby_s]`
* Set key value to one of `shelter`, `regbreeder` or `owner`

**Comment by jackm** [comment]
Yes you're right, I didn't see that you had that field in there before.

What you did by looking at the HTTP POST request for the parameter names is exactly what I end up doing when I have to post an ad that requires some additional unique parameters. The `build_ad` subcommand is supposed to make this process more automated, but it still doesn't yet cover all of the corner cases as you've seen.
